### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by bivald** [codebynumbers/ftpretty#19]
I seem to be getting a problem using ftpretty (in this case on Py 2.7):

    Traceback (most recent call last):
     File "<builtin>/app_main.py", line 75, in run_toplevel
     File "arinc767.py", line 11, in <module>
       import edal
     File "/Users/bivald/epic-data-access-layer/edal/__init__.py", line 20, in <module>
       from ftpretty import ftpretty
     File "build/bdist.macosx-10.10-x86_64/egg/ftpretty.py", line 25, in <module>
      from compat import buffer_type, file_type
   ImportError: No module named compat

When installing via pypi or git (in this case via easy_install on pypy). From what I'm seeing this can be resolved by changing setup.py from:

     py_modules=['ftpretty'],

to:

    py_modules=['ftpretty', 'compat'],

Not sure if that would make setuptools think you are defining the package 'compat' outside of ftpretty. Another solution would be to put the ftpretty.py in a folder named ftpretty with the code in a __init__.py I guess. 

Not sure which is the best way to go, and it could just be me having this issue

**Comment by codebynumbers** [comment]
I think adding compat to py_modules should be ok, although I could not reproduce your issue.

**Comment by codebynumbers** [comment]
new version on pypi
