### ISSUE TITLE
The 't' letter in permissions pt.2

### ISSUE THREAD

**Issue by d4os** [codebynumbers/ftpretty#30]
Unfortunately it's still not working, the 't' letter is 9th letter of permissions (or 8th in computer speech), the test should be
`drwxr-xr-t`
 instead of 
`drwxr-xr-xt`
the 't' isn't an extra letter, it replaces the 'x'. I've made additional research, it turns out [uppercase 'T' also exists](https://unix.stackexchange.com/a/228927), but even that is not all because [uppercase 'S' is also possible](https://en.wikipedia.org/wiki/File_system_permissions), my suggestion would therefore be:
` r'((?:[r-][w-][-xsStT]){3})\s+' + # Permissions [2]`
as seen [here: regexr.com/4klno](https://regexr.com/4klno)

Thanks for the quick response, after creating that issue I've had some fun with ftpretty and it's great.

_Originally posted by @d4os in https://github.com/codebynumbers/ftpretty/issues/29#issuecomment-529512426_

**Comment by codebynumbers** [comment]
Fixed in 0.3.0
