### ISSUE TITLE
How to use a custom port for connection?

### ISSUE THREAD

**Issue by pratham2003** [codebynumbers/ftpretty#32]
I tried passing port as port=22.. It doesn't work..

**Comment by pratham2003** [comment]
I was able to use 
`FTP.port = 22`
`ftp_conn=FTP(...)`

But please let me know if there is a better way.

**Comment by codebynumbers** [comment]
At the moment, no there doesn't seem to be a better way. Would be open to a PR that takes your approach and allows for passing port when initializing ftpretty.
