### ISSUE TITLE
bug in time extraction

### ISSUE THREAD

**Issue by SharonBrizinov** [codebynumbers/ftpretty#39]
https://github.com/codebynumbers/ftpretty/blob/bd2104f8c02e4492f38bfcc1de9e0af2f77d778c/ftpretty.py#L295

12:XX pm will cause issue because it doesn't overflow
12:XX pm will become 24:XX instead of 00:XX

**Comment by SharonBrizinov** [comment]
I've fixed function, added a couple of more touches to it and used it in my project (with credit to you)
take a look here - 
https://github.com/SharonBrizinov/s3viewer/blob/main/src/providers/ftp_provider.py

**Comment by codebynumbers** [comment]
Will copy fix into next version. thanks.
