### ISSUE TITLE
Get recursively

### ISSUE THREAD

**Issue by Paradoxis** [codebynumbers/ftpretty#41]
Hi, I love the syntax of the library over Python's own implementation, could you consider adding a `get_tree` or `get(recursive=True)` function?

**Comment by vgdh** [comment]
it would be good!

**Comment by codebynumbers** [comment]
Like the idea, just need to find the time do it, should be very similar to  upload_tree() if anyone wants to take stab at it.

**Comment by codebynumbers** [comment]
Added in version 0.4.0
