### ISSUE TITLE
Contribution?

### ISSUE THREAD

**Issue by Exvixcity** [codebynumbers/ftpretty#45]
Hello! I have recently downloaded the "ftpretty.py" and "compat.py" files and made a bunch of changes to it, e.g. adding checks to see if something is a file or not, adding support for the "with" keyword and getting the server welcome message.
Is it possible to integrate my changes into ftpretty?

**Comment by codebynumbers** [comment]
Possibly, please open a pull request, 1 feature at a time. Please include the purpose and reasoning by the change, along with tests. I will review the PR to see if it something that would add benefit to the library.
